### ISSUE TITLE
Can't install this thing

### ISSUE THREAD

**Issue by anasroubi** [vah13/BurpCRLFPlugin#1]
Can you please write some details about installing this plugin and thanks a lot

**Comment by vah13** [comment]
1. you need to download https://github.com/vah13/BurpCRLFPlugin/releases/download/v1.1/crlf_release.jar  (request Java 8) plugin or download and compile plugin from git source code.
2. Need run Burp Extender / Extensions / Add
3. The plugin will automatically check all request in active scan mode.
